name: Moma Fast Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Checkout Repo
        uses: actions/checkout@v4

      - name: ðŸš€ Instant FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.momaexcursiones.co
          username: deploy@momaexcursiones.co
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./out/
          server-dir: /public_html/
          # Esto evita subir archivos innecesarios y acelera el proceso
          exclude: |
            **/.git*
            **/.git*/**
            node_modules/**
            .github/**
